Add support for resolving 'latest:X' in .tool-versions
asdf-community/asdf-direnv pull request #136
Opened 2022-04-04 02:23 UTC by amrox

## Overview

asdf supports specifying a version like 'latest:3' which means the latest stable version, in the 3.x.y series of a program. This adds support for this feature in this plugin.

Also adds a test, and support for `list-all` in the test dummy plugin. `list-all` is called by asdf internally when using the 'latest:X' format.

### Example

`.tool-versions`:
```
shfmt latest:3
```

### Before

```
❯ direnv reload
direnv: using asdf
direnv: Creating env file /Users/amrox/.cache/asdf-direnv/env/2823755088-4041093217-1715707609-2415048703
direnv:  latest:3 not installed. Run 'asdf install' and then 'direnv reload'.
direnv: loading ~/.cache/asdf-direnv/env/2823755088-4041093217-1715707609-2415048703
direnv: using asdf shfmt latest:3
direnv: loading ~/tmp/asdf-direnv-latest/.envrc

❯ which shfmt
shfmt not found
```

### After

```
❯ direnv reload
direnv: using asdf
direnv: Creating env file /Users/amrox/.cache/asdf-direnv/env/2823755088-4041093217-3420899879-2415048703
direnv: loading ~/.cache/asdf-direnv/env/2823755088-4041093217-3420899879-2415048703
direnv: using asdf shfmt latest:3
direnv: loading ~/tmp/asdf-direnv-latest/.envrc
direnv: export ~PATH

❯ which shfmt
/Users/amrox/.asdf/installs/shfmt/3.4.3/bin/shfmt
```

## Implementation notes

- The technique used to translate 'latest:X' into an actual version is [the same as in asdf itself.](https://github.com/asdf-vm/asdf/blob/7493f4099c844e40af72d7f05635d7991a463d1a/lib/commands/command-install.bash#L161)

## Interesting/controversial decisions

- maybe adding `list-all` in the dummy test plugin?

## Test coverage

I included a new test, and support for 'list-all' in the dummy plugin. `list-all` is necessary to resolve the latest:X version.

New test is 22

```
❯ make test
env TERM=xterm bats -F tap test
1..28
ok 1 install command fails if the input is not version number
ok 2 local command touches .tool-versions and .envrc
ok 3 local command touches .tool-versions and .envrc - multiple tools
ok 4 setup bash modifies rcfile
ok 5 setup zsh modifies rcfile
ok 6 setup fish modifies rcfile
ok 7 can re-run setup
ok 8 calling without arguments prints help
ok 9 calling with --help prints help
ok 10 calling with -h prints help
ok 11 calling with plugin name but without version fails
ok 12 can specify a one-shot command to run
ok 13 dummy 1.0 is available via asdf exec
ok 14 direnv loads simple envrc
ok 15 use multiple versions for same plugin - multiline
ok 16 use multiple versions for same plugin - inline
ok 17 use asdf - makes global tools available in PATH
ok 18 use asdf - makes local tools available in PATH
ok 19 use asdf - prepends plugin custom shims to PATH
ok 20 use asdf - exports plugin custom env not only PATH
ok 21 use asdf - determines version from tool-versions
ok 22 use asdf - resolves latest:X version from tool-versions
ok 23 use asdf - watches tool-versions for changes
ok 24 use asdf - watches plugin legacy file for changes
ok 25 use asdf - activates currently selected plugins
ok 26 use asdf - watches selection files
ok 27 use asdf - watches legacy files
ok 28 use asdf - sets local tools on PATH before global tools
```

## Loose ends

 n/a

2022-04-04 04:02 UTC, vic requested changes

2022-04-04 04:02 UTC, vic commented on test/test_helpers.bash
> +  local version_file="${ASDF_DATA_DIR}/plugins/${plugin_name}/data/versions.txt"
remove this `versions.txt` file, see comment below.

2022-04-04 04:02 UTC, vic commented on test/test_helpers.bash
> +  if test -n "$list_all_path"; then
This if will always evaluate it's true branch, you can remove the conditional.

2022-04-04 04:04 UTC, vic commented
Hey @amrox, just added a few comments, but in general this is a great feature to have, nice work!

Could you also add an entry to change log, please?

Thank you again :)

2022-04-05 01:53 UTC, amrox commented
@vic Thanks for the quick review and catching my silly mistakes :) I believe I had incorporated all your feedback.

2022-04-05 04:11 UTC, vic commented
looks great! merging now, thank you :)

2022-04-05 04:11 UTC, merged